[package]
name = "cryptonote-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
sprs = "0.11.0"
petgraph = "^0.6.2"
clap = "^3.0"
rand = "^0.8.5"

[lib]
name = "xmrtrace"
path = "src/lib.rs"